client_radar:
  filters:
    okved_codes:
      - "46.3"
      - "46.4"
      - "46.7"
      - "46.2"
      - "10."
    regions:
      - "Курская область"
    employees_number:
      min: 15
      max: null
    statuses:
      - "Действующая"
    legal_form:
      - "ООО"
      - "АО"
    revenue:
      min: 100000000
      max: null
    contacts:
      phone: true
      email: true
      site: true

  extracted_data:
    - "Название"
    - "Директор"
    - "Телефоны"
    - "Email"
    - "Выручка"
    - "Число сотрудников"
    - "ОКВЭД"
