client_radar:
  filters:
    okved_codes:
      - "46.3"
      - "46.4"
      - "46.7"
      - "46.2"
      - "10."
    regions:
      - "Курская область"
    employees_number:
      min: 15
      max: null
    statuses:
      - "Действующая"
    # Фильтр по правовым формам по ОКОПФ в данный момент реализован хардкодом.
    legal_forms:
      - "ООО — Общества с ограниченной ответственностью"
      - "АО — Акционерные общества"
    revenue:
      min: 100000000
      max: null
    contacts:
      - "Телефон"
      - "Электронная почта"
      - "Сайт"

  extracted_data:
    - "Название"
    - "Директор"
    - "Телефоны"
    - "Email"
    - "Выручка"
    - "Число сотрудников"
    - "ОКВЭД"
