"""Changed field name

Revision ID: 1b92777ed29b
Revises: 86e70f50e531
Create Date: 2026-07-15 23:29:11.235617

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1b92777ed29b"
down_revision: Union[str, Sequence[str], None] = "86e70f50e531"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies", sa.Column("sites", sa.String(length=255), nullable=False)
    )
    op.drop_column("companies", "site")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies", sa.Column("site", sa.VARCHAR(length=255), nullable=False)
    )
    op.drop_column("companies", "sites")
    # ### end Alembic commands ###
