"""Initial

Revision ID: 356f7394e58a
Revises:
Create Date: 2026-07-14 18:12:21.880176

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "356f7394e58a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("director", sa.String(), nullable=False),
        sa.Column("phone_numbers", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("site", sa.String(), nullable=False),
        sa.Column("revenue", sa.Integer(), nullable=False),
        sa.Column("profit", sa.Integer(), nullable=False),
        sa.Column("employees_number", sa.Integer(), nullable=False),
        sa.Column("okved", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("companies")
    # ### end Alembic commands ###
