"""Changed field types, added new models

Revision ID: 4b2b9510a0ab
Revises: 1b92777ed29b
Create Date: 2026-07-15 23:53:27.750949

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4b2b9510a0ab"
down_revision: Union[str, Sequence[str], None] = "1b92777ed29b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "company_sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("site", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("companies", "sites")
    op.drop_column("companies", "email")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "companies", sa.Column("email", sa.VARCHAR(length=255), nullable=False)
    )
    op.add_column(
        "companies", sa.Column("sites", sa.VARCHAR(length=255), nullable=False)
    )
    op.drop_table("company_sites")
    op.drop_table("company_emails")
    # ### end Alembic commands ###
