"""Added models import

Revision ID: 63979fff3c79
Revises: ecaefcf5f1a5
Create Date: 2026-07-15 18:14:01.129032

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "63979fff3c79"
down_revision: Union[str, Sequence[str], None] = "ecaefcf5f1a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("director", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("site", sa.String(length=255), nullable=False),
        sa.Column("revenue", sa.Integer(), nullable=False),
        sa.Column("profit", sa.Integer(), nullable=False),
        sa.Column("employees_number", sa.Integer(), nullable=False),
        sa.Column("okved", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("ogrn", sa.String(length=13), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ogrn"),
    )
    op.create_table(
        "company_phones",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_id", sa.Integer(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_phones")
    op.drop_table("companies")
    # ### end Alembic commands ###
