"""field types have been changed

Revision ID: 86e70f50e531
Revises: 63979fff3c79
Create Date: 2026-07-15 18:25:47.761631

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86e70f50e531"
down_revision: Union[str, Sequence[str], None] = "63979fff3c79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("companies") as batch_op:
        batch_op.alter_column(
            "revenue",
            existing_type=sa.Integer(),
            type_=sa.String(255),
        )
    with op.batch_alter_table("companies") as batch_op:
        batch_op.alter_column(
            "profit",
            existing_type=sa.Integer(),
            type_=sa.String(255),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "companies",
        "profit",
        existing_type=sa.String(length=255),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.alter_column(
        "companies",
        "revenue",
        existing_type=sa.String(length=255),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
