"""director and employees_number fields is nullable=True now

Revision ID: cc39eb45100f
Revises: 4b2b9510a0ab
Create Date: 2026-07-15 23:57:28.698553

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cc39eb45100f"
down_revision: Union[str, Sequence[str], None] = "4b2b9510a0ab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("companies") as batch_op:
        batch_op.alter_column(
            "director",
            existing_type=sa.VARCHAR(length=255),
            nullable=True,
        )
    with op.batch_alter_table("companies") as batch_op:
        batch_op.alter_column(
            "employees_number",
            existing_type=sa.VARCHAR(length=255),
            nullable=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "companies", "employees_number", existing_type=sa.INTEGER(), nullable=False
    )
    op.alter_column(
        "companies", "director", existing_type=sa.VARCHAR(length=255), nullable=False
    )
    # ### end Alembic commands ###
