"""Added ogrn field and fields length limitation

Revision ID: ecaefcf5f1a5
Revises: bba12641b191
Create Date: 2026-07-15 17:16:53.747805

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ecaefcf5f1a5"
down_revision: Union[str, Sequence[str], None] = "bba12641b191"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("company_phones")
    op.drop_table("companies")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(), nullable=False),
        sa.Column("director", sa.VARCHAR(), nullable=False),
        sa.Column("email", sa.VARCHAR(), nullable=False),
        sa.Column("site", sa.VARCHAR(), nullable=False),
        sa.Column("revenue", sa.INTEGER(), nullable=False),
        sa.Column("profit", sa.INTEGER(), nullable=False),
        sa.Column("employees_number", sa.INTEGER(), nullable=False),
        sa.Column("okved", sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "company_phones",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("company_id", sa.INTEGER(), nullable=False),
        sa.Column("phone_number", sa.VARCHAR(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
